# Generated by Django 2.2.6 on 2019-10-24 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('RFC', models.CharField(max_length=100, verbose_name='rfc')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('code_postal', models.IntegerField(verbose_name='Codigo Postal')),
                ('phone', models.BigIntegerField(verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='Correo')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clients.Clients', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['created_on'],
            },
        ),
    ]
