# Generated by Django 2.2.6 on 2019-10-24 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('first_name', models.CharField(max_length=40, verbose_name='Apellido Paterno')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellido Materno')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(verbose_name='Telefono')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.Clients', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='fiscalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('state', models.CharField(max_length=40, verbose_name='Estado')),
                ('code_postal', models.IntegerField(verbose_name='Codigo Postal')),
                ('phone', models.BigIntegerField(verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='Correo')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.Clients', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Datos fiscales',
                'verbose_name_plural': 'Datos Fiscales',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.Clients', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Correo',
                'verbose_name_plural': 'Correos',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='customersAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250, verbose_name='Calle')),
                ('number', models.IntegerField(verbose_name='Numero')),
                ('suburb', models.CharField(max_length=50, verbose_name='Colonia')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('code_postal', models.IntegerField(verbose_name='Codigo Postal')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.Clients', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Direccion de Cliente',
                'verbose_name_plural': 'Direcciones de Clientes',
                'ordering': ['created_on'],
            },
        ),
    ]
